import type { Encounter } from '../types'

export const ENCOUNTERS: Record<string, Encounter> = {
  intro_wrong_card: {
    id: 'intro_wrong_card',
    title: 'The Wrong Card',
    description:
      'Anjali handed her husband\'s card to the registrar. The claim went out under his subscriber id and bounced. One amend on Box 1a fixes it.',
    surfaceSymptom: 'Patient cannot be identified as our insured',
    rootCause: 'patient',
    carcCode: 'CO-31',
    carcName: 'Patient cannot be identified as our insured',
    watchpoint: 'The 271 eligibility response is the source of truth — not the card photocopy.',
    level: 1,
    archetype: 'Wrong Card',
    wing: 'eligibility',
    codexOnSight: 'obstacle_intro_wrong_card',
    prototypeIframeUrl: '/intro-prototype.html',
    cashRecovered: 387,
    caseId: 'case_intro_patel',
    highlightedBoxes: ['1a'],
    payerNote:
      'Subscriber AET447821903 (PATEL, RAVI) — dependent ANJALI PATEL listed under separate subscriber id AET447821491. Resubmit with Box 1a corrected.',
  },
  co_50: {
    id: 'co_50',
    title: 'Medical Necessity Wraith',
    description:
      'A semi-transparent figure of half-finished documentation. Won\'t resolve until you assemble enough supporting evidence — wrong moves only feed it.',
    surfaceSymptom: 'Payer denies medical necessity',
    rootCause: 'provider',
    carcCode: 'CO-50',
    carcName: 'Not medically necessary',
    watchpoint: 'CDI before coding prevents this; appeals after submission rarely fix it.',
    level: 12,
    archetype: 'Medical Necessity Wraith',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_50',
    prototypeIframeUrl: '/wraith-prototype.html',
    unlocksOnDefeat: ['medical_policy'],
    caseId: 'case_wraith_walker',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'TTE 93306 not medically necessary for I50.9 (heart failure, unspecified) without supporting evidence of LVEF<35% per LCD L33526.',
  },
  co_97: {
    id: 'co_97',
    title: 'Bundling Beast',
    description: 'Two services on the same day fused into one. The E&M was significant and separate, but the modifier is missing.',
    surfaceSymptom: 'Payer bundled the services together',
    rootCause: 'provider',
    carcCode: 'CO-97',
    carcName: 'Bundled / included',
    watchpoint: 'Modifier 25 / 59 logic is a coding-team responsibility.',
    level: 9,
    archetype: 'Bundling Beast',
    wing: 'coding',
    codexOnSight: 'obstacle_co_97',
    prototypeIframeUrl: '/bundle-prototype.html',
    caseId: 'case_bundle_kim',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 99214 bundled into 11102 per NCCI edit. Append modifier -25 to the E&M to indicate a significant, separately identifiable service.',
  },
  co_197: {
    id: 'co_197',
    title: 'Prior Auth Gatekeeper',
    description:
      'A bureaucratic gate stands between the claim and adjudication. Every other move just bounces off the closed gate. File the 278 to bring it down.',
    surfaceSymptom: 'No prior auth on file',
    rootCause: 'payer',
    carcCode: 'CO-197',
    carcName: 'Precertification absent',
    watchpoint: 'Only fixable upstream — get the 278 before the visit.',
    level: 5,
    archetype: 'Prior Auth Gatekeeper',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_197',
    prototypeIframeUrl: '/gatekeeper-prototype.html',
    unlocksOnDefeat: ['prior_auth_278'],
    caseId: 'case_gatekeeper_okafor',
    highlightedBoxes: ['24D-1'],
    payerNote:
      'CPT 72148 (MRI lumbar) requires prior authorization on file before adjudication. No 278 received — claim denied per UHC commercial policy CMP.PHARM.213.',
  },
  co_16_swarm: {
    id: 'co_16_swarm',
    title: 'Documentation Sprite Swarm',
    description:
      'Tiny gremlins keep peeling off a leaking chart. Each one is a missing-info reject. Killing them is endless until you patch the source upstream.',
    surfaceSymptom: '277CA front-end rejections piling up',
    rootCause: 'vendor',
    carcCode: 'CO-16',
    carcName: 'Missing/invalid information',
    watchpoint: 'CDI is upstream — patch the chart and the rejects stop. Scrubbing only sweeps what already came through.',
    level: 13,
    archetype: 'Documentation Sprite Swarm',
    wing: 'coding',
    codexOnSight: 'obstacle_co_16_swarm',
    prototypeIframeUrl: '/swarm-prototype.html',
    cashRecovered: 220,
    unlocksOnDefeat: ['claim_scrubber'],
    caseId: 'case_swarm_yamada',
    highlightedBoxes: ['21A', '24D-1'],
    payerNote:
      'Multiple 277CA rejects on file: missing rendering provider taxonomy and ambiguous diagnosis pointer. Resubmit with corrected loop 2310B PRV segment and specific dx.',
  },
  eligibility_fog: {
    id: 'eligibility_fog',
    title: 'Eligibility Fog',
    description:
      'A swirling gray cloud that hides everything: which payer, which plan, which benefits. Every swing is half-blind until the 270 inquiry burns it off.',
    surfaceSymptom: 'Coverage details unverifiable',
    rootCause: 'system',
    // No CARC — this is a process obstacle, not a denial code.
    watchpoint: '270/271 eligibility verification is cheap and prevents most "denials" from ever happening.',
    level: 3,
    archetype: 'Eligibility Fog',
    wing: 'eligibility',
    codexOnSight: 'obstacle_eligibility_fog',
    prototypeIframeUrl: '/fog-prototype.html',
    cashRecovered: 190,
    unlocksOnDefeat: ['cost_estimate'],
    caseId: 'case_fog_nguyen',
    highlightedBoxes: ['1a', '1'],
    payerNote:
      'Coverage cannot be confirmed for the subscriber on file. Run 270 inquiry to verify active member id and benefits before submission.',
  },
  co_18_doppelganger: {
    id: 'co_18_doppelganger',
    title: 'Duplicate Claim Doppelgänger',
    description:
      'A perfect copy of the claim already in the queue. Hit it with the same tool twice and the move bounces off you.',
    surfaceSymptom: 'Payer flagged the resubmission as a duplicate',
    rootCause: 'system',
    carcCode: 'CO-18',
    carcName: 'Duplicate claim',
    watchpoint: 'Same submission twice = the same denial twice. Vary the approach (837 frequency 7 instead of 1).',
    level: 14,
    archetype: 'Duplicate Claim Doppelgänger',
    wing: 'billing',
    codexOnSight: 'obstacle_co_18_doppelganger',
    prototypeIframeUrl: '/doppelganger-prototype.html',
    cashRecovered: 145,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_doppel_reyes',
    highlightedBoxes: ['1a', '24A-1'],
    payerNote:
      'Claim CLM-2026-03-08-19842 is a duplicate of one already on file. Submit as 837 frequency code 7 (replacement) to resolve.',
  },
  co_29_reaper: {
    id: 'co_29_reaper',
    title: 'Timely Filing Reaper',
    description:
      'A robed bureaucrat with an hourglass-blade. Each turn it sharpens. Time is the weapon, not the claim.',
    surfaceSymptom: 'Claim approaches the timely filing deadline.',
    rootCause: 'payer',
    carcCode: 'CO-29',
    carcName: 'Timely filing limit expired',
    watchpoint:
      'Timely filing is contractual. Once the deadline passes, no appeal will recover the claim.',
    level: 19,
    archetype: 'Timely Filing Reaper',
    wing: 'appeals',
    codexOnSight: 'obstacle_co_29_reaper',
    prototypeIframeUrl: '/reaper-prototype.html',
    cashRecovered: 1400,
    unlocksOnDefeat: ['submit_837i'],
    caseId: 'case_reaper_park',
    highlightedBoxes: ['24A-1'],
    payerNote:
      'Filing limit 180 days from DOS. Current claim filed 195 days post-service — denial per Aetna provider manual §6.4.',
  },
  boss_audit: {
    id: 'boss_audit',
    title: 'The Quarterly Audit',
    description: 'The payer is reviewing every recent claim. Every shortcut you took is about to surface.',
    surfaceSymptom: 'Payer demands documentation for all recent claims',
    rootCause: 'provider',
    carcCode: 'AUDIT',
    carcName: 'Quarterly Payer Audit',
    watchpoint: 'Audit risk is not abstract; it is a real expense. Every shortcut taken in earlier levels comes due here.',
    level: 33,
    archetype: 'The Quarterly Audit',
    wing: 'miracles',
    codexOnSight: 'obstacle_boss_audit',
    prototypeIframeUrl: '/audit-boss-prototype.html',
    cashRecovered: 8400,
    caseId: 'case_audit_finale',
    highlightedBoxes: ['67', '80'],
    payerNote:
      'Pre-payment audit per UHC commercial CMP.AUD.402. Documentation required for all inpatient stays > $5K within review window. Append rendering provider attestation, complete H&P, and discharge summary; verify principal dx supports DRG assignment.',
  },
  underpayment_specter: {
    id: 'underpayment_specter',
    title: 'Underpayment Specter',
    description: 'A claim that paid — but for less than the contract says. The shortfall hides inside a CO-45 adjustment.',
    surfaceSymptom: 'Contract-vs-paid variance flagged in monthly report',
    rootCause: 'payer',
    watchpoint: 'Underpayments are millions in aggregate. Read line-level numbers, not just batch totals.',
    level: 26,
    archetype: 'Underpayment Specter',
    wing: 'reconsideration',
    codexOnSight: 'obstacle_underpayment_specter',
    prototypeIframeUrl: '/specter-prototype.html',
    cashRecovered: 28,
  },
  lighthouse_charity: {
    id: 'lighthouse_charity',
    title: 'Lighthouse',
    description: 'A patient who needs the hospital\'s financial-assistance program applied correctly. The only encounter that\'s restorative, not adversarial.',
    surfaceSymptom: 'Patient cannot pay; uninsured at time of service',
    rootCause: 'patient',
    watchpoint: 'Charity care is the active path. Bad debt and payment-plan-only are passive failures dressed up as work.',
    level: 10,
    archetype: 'Lighthouse',
    wing: 'patient_services',
    codexOnSight: 'obstacle_lighthouse',
    prototypeIframeUrl: '/lighthouse-prototype.html',
    cashRecovered: 0,
  },
  surprise_bill_specter: {
    id: 'surprise_bill_specter',
    title: 'Surprise Bill Specter',
    description: 'An out-of-network ancillary bill in an in-network ER. NSA-protected; the patient owes in-network cost-share, not the OON balance.',
    surfaceSymptom: 'Patient received an OON balance bill from an ancillary provider',
    rootCause: 'vendor',
    watchpoint: 'NSA caps patient responsibility at in-network. Sending NSA-protected bills to collections is itself a regulatory violation.',
    level: 20,
    archetype: 'Surprise Bill Specter',
    wing: 'patient_services',
    codexOnSight: 'obstacle_surprise_bill',
    prototypeIframeUrl: '/surprise-bill-prototype.html',
    cashRecovered: 0,
  },

  // === Catalog encounters — mounted via PrototypeIframeScene ===
  // These wrap the standalone /<case>-prototype.html pages. The
  // page emits a `case-completed` postMessage on victory; the scene
  // (PrototypeIframeScene) runs the game-side submit plumbing.
  catalog_asp_wac_apothecary: {
    id: 'catalog_asp_wac_apothecary',
    title: 'ASP / WAC Apothecary',
    description: 'Part B drug pricing dispute. ASP vs WAC, J-code unit dose, NDC↔HCPCS crosswalk.',
    surfaceSymptom: 'J-code reimbursement below ASP+6%',
    rootCause: 'payer',
    watchpoint: 'Drug pricing is published quarterly. The dispute is almost always in the unit math.',
    level: 2,
    archetype: 'Apothecary',
    wing: 'reconsideration',
    prototypeIframeUrl: '/asp-wac-apothecary-prototype.html',
  },
  catalog_stoploss_reckoner: {
    id: 'catalog_stoploss_reckoner',
    title: 'Stoploss Reckoner',
    description: 'High-cost case crossing the stoploss threshold. % outlier vs charges audit.',
    surfaceSymptom: 'Case rate underpayment on a high-cost claim',
    rootCause: 'payer',
    watchpoint: 'Stoploss thresholds are contract-specific. Read the actual clause, not the summary.',
    level: 4,
    archetype: 'Reckoner',
    wing: 'reconsideration',
    prototypeIframeUrl: '/stoploss-reckoner-prototype.html',
  },
  catalog_form_mirror: {
    id: 'catalog_form_mirror',
    title: 'Form Mirror',
    description: 'CMS-1500 vs UB-04 — which form does this service belong on?',
    surfaceSymptom: 'Claim routed to the wrong adjudication path',
    rootCause: 'provider',
    watchpoint: 'Form selection is determined by billing entity, not by service.',
    level: 6,
    archetype: 'Form Mirror',
    wing: 'eligibility',
    prototypeIframeUrl: '/form-mirror-prototype.html',
  },
  catalog_outpatient_surgery_grouper: {
    id: 'catalog_outpatient_surgery_grouper',
    title: 'Outpatient Surgery Grouper',
    description: 'APC packaging for outpatient surgery — status indicators + bundling rules.',
    surfaceSymptom: 'Outpatient surgery line packaged into a primary that shouldn\'t apply',
    rootCause: 'payer',
    watchpoint: 'APC status indicators drive everything. Mismatched indicators are the most common denial.',
    level: 7,
    archetype: 'Grouper',
    wing: 'reconsideration',
    prototypeIframeUrl: '/outpatient-surgery-grouper-prototype.html',
  },
  catalog_no_show_bill: {
    id: 'catalog_no_show_bill',
    title: 'No-Show Bill',
    description: 'A patient missed an appointment. Decide whether the fee gets waived or enforced.',
    surfaceSymptom: 'Patient escalation on a no-show fee',
    rootCause: 'patient',
    watchpoint: 'The script is the policy. Tone matters as much as the math.',
    level: 8,
    archetype: 'Lighthouse companion',
    wing: 'patient_services',
    prototypeIframeUrl: '/no-show-bill-prototype.html',
  },
  catalog_gfe_oracle: {
    id: 'catalog_gfe_oracle',
    title: 'Good Faith Estimate Oracle',
    description: 'GFE-vs-bill mismatch. Patient appeal path opens at the $400 threshold.',
    surfaceSymptom: 'Patient bill exceeds Good Faith Estimate',
    rootCause: 'provider',
    watchpoint: 'Itemization gaps between GFE and final bill drive most disputes.',
    level: 11,
    archetype: 'Oracle',
    wing: 'appeals',
    prototypeIframeUrl: '/gfe-oracle-prototype.html',
  },
  catalog_implant_carveout_specter: {
    id: 'catalog_implant_carveout_specter',
    title: 'Implant Carve-Out Specter',
    description: 'Implant cost above stoploss — invoice carve-out missed by the contract.',
    surfaceSymptom: 'Surgical case underpayment on the implant line',
    rootCause: 'payer',
    watchpoint: 'Carve-out clauses trigger above thresholds the contract team didn\'t flag.',
    level: 15,
    archetype: 'Specter',
    wing: 'reconsideration',
    prototypeIframeUrl: '/implant-carveout-specter-prototype.html',
  },
  catalog_credentialing_lattice: {
    id: 'catalog_credentialing_lattice',
    title: 'Credentialing Lattice',
    description: 'New hire whose credentialing paperwork is still in flight; claim denied.',
    surfaceSymptom: 'Claim denied: provider not credentialed with this payer',
    rootCause: 'system',
    watchpoint: 'Retro-credentialing is sometimes available. Sometimes the covering credentialed provider is the path.',
    level: 16,
    archetype: 'Lattice',
    wing: 'eligibility',
    prototypeIframeUrl: '/credentialing-lattice-prototype.html',
  },
  catalog_carveout_phantom: {
    id: 'catalog_carveout_phantom',
    title: 'Carve-Out Phantom',
    description: 'Two bills for one ER visit. NSA carve-out routes the OON physician fight to IDR.',
    surfaceSymptom: 'OON physician bill at in-network facility',
    rootCause: 'vendor',
    watchpoint: 'Patient cost-share at in-network. OON ↔ payer arbitration via IDR.',
    level: 17,
    archetype: 'Phantom',
    wing: 'reconsideration',
    prototypeIframeUrl: '/carveout-phantom-prototype.html',
  },
  catalog_cpt_licensure_mire: {
    id: 'catalog_cpt_licensure_mire',
    title: 'CPT Licensure Mire',
    description: 'AMA CPT licensing edges — code mapping, derivative-work limits, public-domain alternatives.',
    surfaceSymptom: 'Coding tool flagged a licensing question',
    rootCause: 'system',
    watchpoint: 'AMA owns CPT. Derivative works need licensing. HCPCS Level II is public-domain for some equivalents.',
    level: 18,
    archetype: 'Mire',
    wing: 'reconsideration',
    prototypeIframeUrl: '/cpt-licensure-mire-prototype.html',
  },
  catalog_ob_perdiem_specter: {
    id: 'catalog_ob_perdiem_specter',
    title: 'OB Per-Diem Specter',
    description: 'OB per-diem with C-section escalator — payer paid the base rate only.',
    surfaceSymptom: 'L&D per-diem underpayment on a C-section case',
    rootCause: 'payer',
    watchpoint: 'Escalators don\'t always propagate through the rate calc. Pull the contract clause.',
    level: 21,
    archetype: 'Specter',
    wing: 'reconsideration',
    prototypeIframeUrl: '/ob-perdiem-specter-prototype.html',
  },
  catalog_phantom_patient: {
    id: 'catalog_phantom_patient',
    title: 'Phantom Patient',
    description: 'Identity-matching collision — two patients, one demographic profile.',
    surfaceSymptom: 'Two patient charts collapsed into a single MRN',
    rootCause: 'system',
    watchpoint: 'Merging two charts wrongly is worse than the original collision. Resolve at the timeline.',
    level: 22,
    archetype: 'Phantom',
    wing: 'eligibility',
    prototypeIframeUrl: '/phantom-patient-prototype.html',
  },
  catalog_risk_adj_hollow: {
    id: 'catalog_risk_adj_hollow',
    title: 'Risk Adjustment Hollow',
    description: 'HCC capture — chronic condition coded once a year, dropped the next, RAF score evaporates.',
    surfaceSymptom: 'Medicare Advantage RAF score dropped year-over-year',
    rootCause: 'provider',
    watchpoint: 'Chronic conditions must be coded every year. Documentation supports the capture.',
    level: 23,
    archetype: 'Hollow',
    wing: 'reconsideration',
    prototypeIframeUrl: '/risk-adj-hollow-prototype.html',
  },
  catalog_chemo_bundle_specter: {
    id: 'catalog_chemo_bundle_specter',
    title: 'Chemo Bundle Specter',
    description: 'Chemotherapy bundled into the case rate; admin code dropped, claim under-pays.',
    surfaceSymptom: 'Oncology case revenue capture missing the chemo admin units',
    rootCause: 'provider',
    watchpoint: 'Admin codes (96413/96415) propagate separately from the drug. Check each.',
    level: 24,
    archetype: 'Specter',
    wing: 'reconsideration',
    prototypeIframeUrl: '/chemo-bundle-specter-prototype.html',
  },
  catalog_two_midnight_mire: {
    id: 'catalog_two_midnight_mire',
    title: 'Two-Midnight Mire',
    description: 'Inpatient vs observation — Medicare 2-midnight rule + medical-necessity overlay.',
    surfaceSymptom: 'Medicare denial of inpatient status; observation push-back',
    rootCause: 'payer',
    watchpoint: 'Clinical narrative justifying inpatient is the defense. The 2-midnight rule is the framing.',
    level: 25,
    archetype: 'Mire',
    wing: 'reconsideration',
    prototypeIframeUrl: '/two-midnight-mire-prototype.html',
  },
  catalog_cob_cascade_spider: {
    id: 'catalog_cob_cascade_spider',
    title: 'COB Cascade Spider',
    description: 'Multi-payer coordination of benefits — Medicare + retiree + spouse plan cascade.',
    surfaceSymptom: 'Three payers all claiming secondary',
    rootCause: 'system',
    watchpoint: 'Birthday rule, employer-vs-retiree, Medicare secondary. The 271s often disagree.',
    level: 27,
    archetype: 'Spider',
    wing: 'eligibility',
    prototypeIframeUrl: '/cob-cascade-spider-prototype.html',
  },
  catalog_case_rate_specter: {
    id: 'catalog_case_rate_specter',
    title: 'Case-Rate Specter',
    description: 'Case-rate vs per-diem mismatch — multi-day stay paid as a single bundle.',
    surfaceSymptom: 'Long stay paid as one case rate',
    rootCause: 'payer',
    watchpoint: 'Case-rate vs per-diem switch is in the contract. LOS threshold matters.',
    level: 28,
    archetype: 'Specter',
    wing: 'reconsideration',
    prototypeIframeUrl: '/case-rate-specter-prototype.html',
  },
  catalog_mrf_cartographer: {
    id: 'catalog_mrf_cartographer',
    title: 'MRF Cartographer',
    description: 'Read the payer rate sheet, find the negotiated rate hidden in 8 GB of JSON.',
    surfaceSymptom: 'Contracted rate disputed; need MRF evidence',
    rootCause: 'payer',
    watchpoint: 'MRFs are CMS-required. Some publish in formats that are technically compliant but practically useless.',
    level: 29,
    archetype: 'Cartographer',
    wing: 'appeals',
    prototypeIframeUrl: '/mrf-cartographer-prototype.html',
  },
  catalog_idr_crucible: {
    id: 'catalog_idr_crucible',
    title: 'IDR Crucible',
    description: 'Baseball-style arbitration — submit one number, pick a number, defend the math.',
    surfaceSymptom: 'NSA IDR submission deadline',
    rootCause: 'payer',
    watchpoint: 'QPA is the benchmark. The closer your number is to QPA, the more often you win.',
    level: 30,
    archetype: 'Crucible',
    wing: 'appeals',
    prototypeIframeUrl: '/idr-crucible-prototype.html',
  },
  catalog_three_forty_b_specter: {
    id: 'catalog_three_forty_b_specter',
    title: '340B Specter',
    description: '340B-eligible drug paid at non-340B rate post-Becerra clawback.',
    surfaceSymptom: '340B drug reimbursement underpayment',
    rootCause: 'payer',
    watchpoint: 'Becerra v. AHA changed the rules. Check eligibility + DOS against the policy.',
    level: 31,
    archetype: 'Specter',
    wing: 'reconsideration',
    prototypeIframeUrl: '/three-forty-b-specter-prototype.html',
  },
  catalog_hipaa_spider: {
    id: 'catalog_hipaa_spider',
    title: 'HIPAA Spider',
    description: 'Breach response — four-factor assessment, notification thresholds, OCR follow-up.',
    surfaceSymptom: 'PHI disclosure incident reported',
    rootCause: 'system',
    watchpoint: 'Don\'t say "breach" until the four-factor assessment is complete.',
    level: 32,
    archetype: 'Spider',
    wing: 'appeals',
    prototypeIframeUrl: '/hipaa-spider-prototype.html',
  },
}

export const ENCOUNTER_LIST = Object.values(ENCOUNTERS)
