import type { LevelDef } from '../types'

// 33-level arc, one level per Case. Authored in the order defined
// by `src/content/case-order.ts`.
//
// Each level binds to exactly one case + one encounter id. Every
// playable encounter routes to PrototypeIframeScene via the
// `prototypeIframeUrl` field on its Encounter entry in enemies.ts —
// the encounter appears in `encounters: []` here, and engagement
// mounts its standalone Case prototype in an iframe.
//
// NPC handoff per level follows district affinity:
//   eligibility → Kim (Registration) / Anjali (L1 only)
//   coding      → Pat (HIM / Registration earlier)
//   billing     → Alex (Main Hub / Billing) / Jordan (PFS at L20+)
//   appeals     → Sam (Patient Services) / Martinez (Prior Auth L5)
//   release-valve → Jordan
// L33 (audit-boss) is Dana on the auditorium stage.

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    title: 'The Wrong Card',
    subtitle: 'Your first day. A claim goes missing.',
    hospitalDescription: 'The revenue cycle office. Desks, monitors, and the hum of fluorescent lights.',
    waitingRoomDescription: 'An endless waiting room. Rows of chairs. A ticket counter that never moves.',
    concepts: ['denial_rate', 'co_109', 'x12_270_271', 'eligibility'],
    encounters: ['intro_wrong_card'],
    cases: ['case_intro_patel'],
    // Dana intentionally not in the L1-32 roster — her in-game
    // presence as a walk-up NPC collided with the "Dana's notebook"
    // briefing voice. She returns at L33 (final) on the auditorium stage.
    npcsActive: ['anjali', 'kim', 'jordan'],
  },
  {
    id: 2,
    title: 'ASP / WAC Apothecary',
    subtitle: 'Part B drug pricing — ASP vs WAC, J-code unit dose, NDC↔HCPCS crosswalk.',
    hospitalDescription: 'Pharmacy is humming. A J-code denial just dropped.',
    waitingRoomDescription: 'Shelves of pill bottles whose labels keep changing prices when you blink.',
    concepts: [],
    encounters: ['catalog_asp_wac_apothecary'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 3,
    title: 'Eligibility Fog',
    subtitle: 'Registration is where claims are born — and where they first break.',
    hospitalDescription: 'The registration desk. Stacks of insurance cards and a line out the door.',
    waitingRoomDescription: 'The chairs have started to face different directions. The clock ticks backwards.',
    concepts: ['cms1500', 'x12_837', 'icd10_cm', 'cpt'],
    encounters: ['eligibility_fog'],
    cases: ['case_fog_nguyen'],
    npcsActive: ['kim', 'alex'],
  },
  {
    id: 4,
    title: 'Stoploss Reckoner',
    subtitle: 'High-cost case crossing the stoploss threshold — % outlier vs charges audit.',
    hospitalDescription: 'A trauma case from last quarter still under review. The number is enormous.',
    waitingRoomDescription: 'A ledger that goes on for floors. Every entry is in the red.',
    concepts: [],
    encounters: ['catalog_stoploss_reckoner'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 5,
    title: 'Prior-Auth Gatekeeper',
    subtitle: 'Prior authorization. The payer says: prove it first.',
    hospitalDescription: 'The pre-certification office. Phone on hold. Fax machine grinding.',
    waitingRoomDescription: 'A gate with no gatekeeper. Forms flutter through the bars.',
    concepts: ['prior_auth', 'x12_278', 'medical_necessity'],
    encounters: ['co_197'],
    cases: ['case_gatekeeper_okafor'],
    npcsActive: ['martinez', 'sam'],
  },
  {
    id: 6,
    title: 'Form Mirror',
    subtitle: 'CMS-1500 vs UB-04 — which form does this service belong on?',
    hospitalDescription: 'Coding asked you to double-check which form a service should have used.',
    waitingRoomDescription: 'Two identical forms facing each other across a hallway, mirror-reflected.',
    concepts: [],
    encounters: ['catalog_form_mirror'],
    cases: [],
    npcsActive: ['pat'],
  },
  {
    id: 7,
    title: 'Outpatient Surgery Grouper',
    subtitle: 'APC grouping for outpatient surgery — packaging rules + status indicators.',
    hospitalDescription: 'Outpatient surgery sent over a case with packaging questions.',
    waitingRoomDescription: 'Operating rooms grouped into clusters that re-group themselves.',
    concepts: [],
    encounters: ['catalog_outpatient_surgery_grouper'],
    cases: [],
    npcsActive: ['pat'],
  },
  {
    id: 8,
    title: 'No-Show Bill',
    subtitle: 'No-show fee policy — when to waive, when to enforce, what the patient hears.',
    hospitalDescription: 'A patient missed an appointment. Front desk asked if you waive the fee.',
    waitingRoomDescription: 'An empty exam room. The chair has been waiting longer than the patient ever did.',
    concepts: [],
    encounters: ['catalog_no_show_bill'],
    cases: [],
    npcsActive: ['jordan'],
  },
  {
    id: 9,
    title: 'Bundling Beast',
    subtitle: 'Clinical documentation meets billing codes.',
    hospitalDescription: 'The HIM department. Charts, codes, and the CDI team.',
    waitingRoomDescription: 'Carbon copies of documents, each slightly different from the last.',
    concepts: ['cdi', 'icd10_cm', 'icd10_pcs', 'modifiers'],
    encounters: ['co_97'],
    cases: ['case_bundle_kim'],
    // Pat (HIM/CDI) gives the bundling case — the objective. Dr.
    // Martinez is ambient scenery in Prior Auth (placed for L5–33 via
    // his `ambient` placement, independent of this list); he has no L9
    // role. He was listed here first, which made the mini-map quest
    // marker target him in Auth instead of Pat. Listing only Pat points
    // the marker at the real objective.
    npcsActive: ['pat'],
  },
  {
    id: 10,
    title: 'Lighthouse',
    subtitle: 'Charity-care / §501(r) financial assistance for a patient with no path to pay.',
    hospitalDescription: 'A patient who can\'t pay. Jordan needs to walk the §501(r) screen.',
    waitingRoomDescription: 'A lighthouse far out, beam sweeping over a sea of unread bills.',
    concepts: ['charity_care', '501r'],
    encounters: ['lighthouse_charity'],
    cases: [],
    npcsActive: ['jordan'],
  },
  {
    id: 11,
    title: 'Good Faith Estimate Oracle',
    subtitle: 'GFE accuracy — patient billed over the threshold, opens the appeal path.',
    hospitalDescription: 'A patient flagged a GFE-vs-bill mismatch. Sam pulled the file.',
    waitingRoomDescription: 'Estimates and bills hanging next to each other, swinging out of sync.',
    concepts: [],
    encounters: ['catalog_gfe_oracle'],
    cases: [],
    npcsActive: ['sam'],
  },
  {
    id: 12,
    title: 'Medical Necessity Wraith',
    subtitle: 'Payer policies are public. Most denials are predictable.',
    hospitalDescription: 'The contract management office. Binders of payer agreements.',
    waitingRoomDescription: 'Infinite shelves of policy manuals. The pages rearrange when you look away.',
    concepts: ['medical_policy', 'fee_schedule', 'contract_terms'],
    encounters: ['co_50'],
    cases: ['case_wraith_walker'],
    npcsActive: ['sam'],
  },
  {
    id: 13,
    title: 'Documentation Sprite Swarm',
    subtitle: 'The claim drops. Clearinghouse, payer, adjudication.',
    hospitalDescription: 'The billing office. Claims queued and dropping.',
    waitingRoomDescription: 'A conveyor belt carrying forms into darkness. Some fall off.',
    concepts: ['x12_837', 'x12_277ca', 'clearinghouse', 'adjudication'],
    encounters: ['co_16_swarm'],
    cases: ['case_swarm_yamada'],
    npcsActive: ['alex', 'pat'],
  },
  {
    id: 14,
    title: 'Doppelgänger',
    subtitle: 'A duplicate that shouldn\'t exist. Version control across submissions.',
    hospitalDescription: 'Registration. The clerk is staring at two claims that look identical.',
    waitingRoomDescription: 'Hallways with mirrored claims hanging on the walls. The reflections don\'t match.',
    concepts: ['x12_837', 'icn', 'frequency_codes', 'duplicate_handling'],
    encounters: ['co_18_doppelganger'],
    cases: ['case_doppel_reyes'],
    npcsActive: ['kim', 'alex'],
  },
  {
    id: 15,
    title: 'Implant Carve-Out Specter',
    subtitle: 'Implant cost above stoploss — invoice carve-out missed by the contract.',
    hospitalDescription: 'A surgical case where the implant invoice should have triggered a carve-out.',
    waitingRoomDescription: 'A scale with the implant on one side and the contract on the other. The contract wins; the math doesn\'t.',
    concepts: [],
    encounters: ['catalog_implant_carveout_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 16,
    title: 'Credentialing Lattice',
    subtitle: 'Provider credentialing gap — claim denied because the doc isn\'t credentialed with this plan yet.',
    hospitalDescription: 'A new hire whose credentialing paperwork is still in flight.',
    waitingRoomDescription: 'Application forms passed from desk to desk. None of the desks belong to a person.',
    concepts: [],
    encounters: ['catalog_credentialing_lattice'],
    cases: [],
    npcsActive: ['kim'],
  },
  {
    id: 17,
    title: 'Carve-Out Phantom',
    subtitle: 'Two bills for one ER visit — NSA carve-out routes the OON physician fight to IDR.',
    hospitalDescription: 'An ER claim where the facility was in-network but the physician group wasn\'t.',
    waitingRoomDescription: 'Two bills for one visit, both saying "you owe." Neither says what you owe for.',
    concepts: [],
    encounters: ['catalog_carveout_phantom'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 18,
    title: 'CPT Licensure Mire',
    subtitle: 'AMA CPT licensing edges — code mapping, derivative-work limits, public-domain alternatives.',
    hospitalDescription: 'A coding question that bumped into AMA licensing terms.',
    waitingRoomDescription: 'A library where every book is licensed for a different number of readings per page.',
    concepts: [],
    encounters: ['catalog_cpt_licensure_mire'],
    cases: [],
    npcsActive: ['pat'],
  },
  {
    id: 19,
    title: 'Timely Filing Reaper',
    subtitle: 'The remittance arrives. Time to read the verdict.',
    hospitalDescription: 'The payment posting area. ERAs streaming in.',
    waitingRoomDescription: 'A courtroom where the judge is a rubber stamp.',
    concepts: ['x12_835', 'carc_rarc', 'remittance', 'adjustment'],
    encounters: ['co_29_reaper'],
    cases: ['case_reaper_park'],
    npcsActive: ['sam', 'jordan'],
  },
  {
    id: 20,
    title: 'Surprise Bill Specter',
    subtitle: 'Patient responsibility. The bill flows downstream.',
    hospitalDescription: 'Patient financial services. The phone rings constantly.',
    waitingRoomDescription: 'A river of paper bills, flowing toward patients who cannot see them coming.',
    concepts: ['cost_share', 'deductible', 'coinsurance', 'copay', 'oop_max', 'nsa'],
    encounters: ['surprise_bill_specter'],
    cases: [],
    npcsActive: ['jordan'],
  },
  {
    id: 21,
    title: 'OB Per-Diem Specter',
    subtitle: 'OB per-diem with C-section escalator — payer paid the base rate only.',
    hospitalDescription: 'L&D billed a per-diem with the C-section escalator; the payer paid base only.',
    waitingRoomDescription: 'A maternity ward where every clock runs at a different rate.',
    concepts: [],
    encounters: ['catalog_ob_perdiem_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 22,
    title: 'Phantom Patient',
    subtitle: 'Identity-matching collision — two patients, one demographic profile.',
    hospitalDescription: 'Two patients matched into the same MRN. Registration caught it on intake.',
    waitingRoomDescription: 'A chart with two faces in the photo. Both blink in unison.',
    concepts: [],
    encounters: ['catalog_phantom_patient'],
    cases: [],
    npcsActive: ['kim'],
  },
  {
    id: 23,
    title: 'Risk Adjustment Hollow',
    subtitle: 'HCC capture — chronic condition coded once a year, dropped the next, RAF score evaporates.',
    hospitalDescription: 'An annual HCC capture review. A chronic that fell off the chart this year.',
    waitingRoomDescription: 'A score that only exists if you say its name. Every year, you have to say it again.',
    concepts: [],
    encounters: ['catalog_risk_adj_hollow'],
    cases: [],
    npcsActive: ['pat'],
  },
  {
    id: 24,
    title: 'Chemo Bundle Specter',
    subtitle: 'Chemotherapy bundled into the case rate; admin code dropped, claim under-pays.',
    hospitalDescription: 'Oncology billed a chemo case; the administration code didn\'t carry through.',
    waitingRoomDescription: 'An IV drip whose contents change every time the bag is replaced. The bill stays the same.',
    concepts: [],
    encounters: ['catalog_chemo_bundle_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 25,
    title: 'Two-Midnight Mire',
    subtitle: 'Inpatient vs observation — Medicare 2-midnight rule + medical-necessity overlay.',
    hospitalDescription: 'A Medicare admission where the 2-midnight expectation is contested.',
    waitingRoomDescription: 'A hospital bed that becomes an observation chair when you look away.',
    concepts: [],
    encounters: ['catalog_two_midnight_mire'],
    cases: [],
    npcsActive: ['pat'],
  },
  {
    id: 26,
    title: 'Underpayment Specter',
    subtitle: 'CO-45 underpayment — contract says one rate, payment shows another.',
    hospitalDescription: 'A CO-45 streak across one payer. The contracted rate isn\'t what landed.',
    waitingRoomDescription: 'A balance that says zero but never zeroes.',
    concepts: [],
    encounters: ['underpayment_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 27,
    title: 'COB Cascade Spider',
    subtitle: 'Multi-payer coordination of benefits — Medicare + retiree + spouse plan cascade.',
    hospitalDescription: 'A patient with three coverages, all of them claiming secondary.',
    waitingRoomDescription: 'A web of insurance cards, each pointing at the next.',
    concepts: [],
    encounters: ['catalog_cob_cascade_spider'],
    cases: [],
    npcsActive: ['kim'],
  },
  {
    id: 28,
    title: 'Case-Rate Specter',
    subtitle: 'Case-rate vs per-diem mismatch — multi-day stay paid as a single bundle.',
    hospitalDescription: 'A multi-day stay paid as one case-rate when per-diem should have applied.',
    waitingRoomDescription: 'A single coin for a stay that lasted a week.',
    concepts: [],
    encounters: ['catalog_case_rate_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 29,
    title: 'MRF Cartographer',
    subtitle: 'Machine-Readable Files — read the payer rate sheet, find the negotiated rate hidden in 8 GB of JSON.',
    hospitalDescription: 'Sam is mapping a payer\'s MRF for a contested rate.',
    waitingRoomDescription: 'A map that updates as you read it. The destination keeps moving.',
    concepts: [],
    encounters: ['catalog_mrf_cartographer'],
    cases: [],
    npcsActive: ['sam'],
  },
  {
    id: 30,
    title: 'IDR Crucible',
    subtitle: 'Baseball-style arbitration — submit one number, pick a number, defend the math.',
    hospitalDescription: 'An IDR submission. Sam is sweating the number.',
    waitingRoomDescription: 'Two envelopes. The arbiter\'s hand hovers between them.',
    concepts: [],
    encounters: ['catalog_idr_crucible'],
    cases: [],
    npcsActive: ['sam'],
  },
  {
    id: 31,
    title: '340B Specter',
    subtitle: '340B-eligible drug paid at non-340B rate post-Becerra clawback.',
    hospitalDescription: 'A 340B-eligible drug paid at the wrong rate. Becerra clawback territory.',
    waitingRoomDescription: 'A pharmacy with two prices on every shelf. Both are correct.',
    concepts: [],
    encounters: ['catalog_three_forty_b_specter'],
    cases: [],
    npcsActive: ['alex'],
  },
  {
    id: 32,
    title: 'HIPAA Spider',
    subtitle: 'Breach response — four-factor assessment, notification thresholds, OCR follow-up.',
    hospitalDescription: 'A faxed PHI page went to the wrong number. Compliance opened the file.',
    waitingRoomDescription: 'A web of fax machines, each one printing the same page.',
    concepts: [],
    encounters: ['catalog_hipaa_spider'],
    cases: [],
    npcsActive: ['sam'],
  },
  {
    id: 33,
    title: 'The Quarterly Audit',
    subtitle: 'Everything you did is under review.',
    hospitalDescription: 'The auditorium. Auditors have arrived.',
    waitingRoomDescription: 'A room of mirrors. Every shortcut reflects back at you.',
    concepts: ['audit', 'compliance', 'upcoding', 'documentation'],
    encounters: ['boss_audit'],
    cases: ['case_audit_finale'],
    npcsActive: ['dana', 'martinez', 'pat', 'sam', 'auditor_carl', 'auditor_chen', 'auditor_rivera', 'auditor_eddi'],
    bossEncounter: 'boss_audit',
  },
]
